#!/data/data/com.termux/files/usr/bin/bash

case $1 in
    -h) echo "Usage: fedora [VERSION|--] [COMMAND]" ;;
    --help) echo "Usage: fedora [VERSION|--] [COMMAND]" ;;
    --) suffix="" ;;
    *) suffix=$1 ;;
esac
shift

CMD="$*"

case "$(uname -o)" in
    Android) LINK2SYMLINK=--link2symlink ;;
    *) ;;
esac

unset LD_PRELOAD && proot ${LINK2SYMLINK} -0 -r ~/fedora$suffix -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b $HOME -w /root /bin/env -i HOME=/root TERM="$TERM" LANG="$LANG" PATH=/usr/bin:/usr/sbin ${CMD:-/bin/bash --login}
