name: check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: test
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y install proot
      - run: ./install.sh f42
      - run: ./fedora cat /etc/os-release
